M48
; DRILL file {KiCad 8.0.2} date 2024-05-28T21:16:51+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-28T21:16:51+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X113.75Y-106.25
X183.75Y-102.0
X183.75Y-152.0
T2
X180.375Y-120.5G85X180.375Y-122.5
G05
M30
